# Wrangler configuration for Cloudflare Pages and D1 Database
name = "raghus-world"
compatibility_date = "2026-06-13"

pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "raghus-world-db"
database_id = "7636f010-2824-4460-8679-20e3840d4dad"
migrations_dir = "./migrations"
